### ISSUE TITLE
May a little bug in ssdg1.sh/ssdg2.sh

### ISSUE THREAD

**Issue by judgingalready** [KaiyangZhou/mixstyle-release#14]
Excuse, when I run this: 

**CUDA_VISIBLE_DEVICES=0 bash ssdg2.sh ssdg_pacs resnet18_ms_l123**

I get this: **ssdg2.sh: line 62: syntax error: unexpected end of file**

at the beginning, I thought it may be **fileformat mistake** that shell was written under windows but used under linux.

However I find there is **"\\"** in line 59, while there isn't in dg.sh. After deleting **"\\"**, code works.

I'm not familiar with Shell, so I don't know if it's a mistake.

Looking forwark to your reply and I will close it soon.

**Comment by KaiyangZhou** [comment]
Yes, it was an error. I've deleted the "\". Please pull the latest code.
