### ISSUE TITLE
也许是我太菜，Dassl框架熟悉起来好麻烦，唉。。。

### ISSUE THREAD

**Issue by BoltenWang-Meta** [KaiyangZhou/mixstyle-release#15]

**Comment by KaiyangZhou** [comment]
My bad. I should have provided a detailed documentation to help you guys navigate the codebase.

Feel free to ask questions here :)

**Comment by Baymine** [comment]
> My bad. I should have provided a detailed documentation to help you guys navigate the codebase.
> 
> Feel free to ask questions here :)

Could you pls explain what is the `imcls/vis.py`  used for? And how to use it exactly? Thank you ~

**Comment by KaiyangZhou** [comment]
please refer to this https://github.com/KaiyangZhou/mixstyle-release/tree/master/imcls#domain-generalization

you only need to specify the path to the extracted features https://github.com/KaiyangZhou/mixstyle-release/blob/master/imcls/vis.py#L17

**Comment by Baymine** [comment]
> please refer to this https://github.com/KaiyangZhou/mixstyle-release/tree/master/imcls#domain-generalization
> 
> you only need to specify the path to the extracted features https://github.com/KaiyangZhou/mixstyle-release/blob/master/imcls/vis.py#L17

Sorry, that is an unnecessary question. Thank you for your reply.
